/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AdminActivityLogTransformer from '#transformers/admin/activity_log_transformer'
import type AdminUserForAdminTransformer from '#transformers/admin/user_for_admin_transformer'
import type RoleTransformer from '#transformers/role_transformer'
import type TodoTransformer from '#transformers/todo_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export namespace Admin {
    export type ActivityLog = InferData<AdminActivityLogTransformer>
    export namespace ActivityLog {
      export type Variants = InferVariants<AdminActivityLogTransformer>
    }
    export type UserForAdmin = InferData<AdminUserForAdminTransformer>
    export namespace UserForAdmin {
      export type Variants = InferVariants<AdminUserForAdminTransformer>
    }
  }
  export type Role = InferData<RoleTransformer>
  export namespace Role {
    export type Variants = InferVariants<RoleTransformer>
  }
  export type Todo = InferData<TodoTransformer>
  export namespace Todo {
    export type Variants = InferVariants<TodoTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
