/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  api: {
    v1: {
      admin: {
        auth: {
          Login: () => import('#controllers/api/v1/admin/auth/login_controller'),
        },
        permissionManagement: {
          Permission: () => import('#controllers/api/v1/admin/permission_management/permission_controller'),
        },
        roleManagement: {
          Roles: () => import('#controllers/api/v1/admin/role_management/roles_controller'),
        },
        userManagement: {
          User: () => import('#controllers/api/v1/admin/user_management/user_controller'),
        },
      },
    },
  },
  Docs: () => import('#controllers/docs_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
