/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  api: {
    v1: {
      admin: {
        activityLogs: {
          ActivityLogs: () => import('#controllers/api/v1/admin/activity_logs/activity_logs_controller'),
        },
        auth: {
          Login: () => import('#controllers/api/v1/admin/auth/login_controller'),
        },
        permissionManagement: {
          Permission: () => import('#controllers/api/v1/admin/permission_management/permission_controller'),
        },
        roleManagement: {
          Roles: () => import('#controllers/api/v1/admin/role_management/roles_controller'),
        },
        userManagement: {
          User: () => import('#controllers/api/v1/admin/user_management/user_controller'),
        },
      },
      user: {
        auth: {
          ForgotPasswords: () => import('#controllers/api/v1/user/auth/forgot_passwords_controller'),
          Login: () => import('#controllers/api/v1/user/auth/login_controller'),
          NewAccount: () => import('#controllers/api/v1/user/auth/new_account_controller'),
        },
        profile: {
          ChangePasswords: () => import('#controllers/api/v1/user/profile/change_passwords_controller'),
          Profile: () => import('#controllers/api/v1/user/profile/profile_controller'),
        },
        tagManagement: {
          Tags: () => import('#controllers/api/v1/user/tag_management/tags_controller'),
        },
        todoManagement: {
          Todos: () => import('#controllers/api/v1/user/todo_management/todos_controller'),
        },
      },
    },
  },
  Docs: () => import('#controllers/docs_controller'),
}
